Repository kimlimjustin/xplorer, pull requests merged in 2021-10, with the labels that each got.

#116 Improve Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#118 update: README.md
  README.md
  docs/static/img/Xplorer_dark+.png
  docs/static/img/Xplorer_dark.png
  docs/static/img/Xplorer_light+.png
  docs/static/img/Xplorer_light.png
Labels: hacktoberfest-accepted

#121 Fix typo in homepage
  docs/src/pages/index.jsx
Labels: documentation

#127 feat: theme customization
  .eslintignore
  .gitignore
  .prettierignore
  docs/docs/common_problems.md
  docs/docs/customization/_category_.json
  docs/docs/customization/theme.md
  lerna.json
  package.json
  packages/generator-xplorer-theme/.eslintignore
  packages/generator-xplorer-theme/.eslintrc.js
  packages/generator-xplorer-theme/.gitignore
  packages/generator-xplorer-theme/LICENSE
  packages/generator-xplorer-theme/README.md
  packages/generator-xplorer-theme/package.json
  packages/generator-xplorer-theme/src/app/index.ts
  packages/generator-xplorer-theme/src/app/templates/package.ejs
  packages/generator-xplorer-theme/src/app/templates/themes.ejs
  packages/generator-xplorer-theme/tsconfig.json
  patches/cpy+8.1.2.patch
  patches/electron-json-storage-sync+1.2.0.patch
  patches/electron-prompt+1.6.2.patch
  patches/fast-glob+2.2.7.patch
  scripts/postinstall.js
  src/Components/Setting/Appearance/Appearance.ts
  src/Components/Theme/theme.ts
  src/Extensions/registerTheme.ts
  src/Typings/electron-json-storage-sync.d.ts
  src/main.ts
  src/preload.ts
  yarn.lock
Labels: UI, hacktoberfest-accepted

#141 Added Active Tab Styling in Settings
  src/Components/Setting/setting.scss
  src/Components/Setting/setting.ts
  src/Components/Theme/theme.json
  src/Components/Theme/theme.ts
  yarn.lock
Labels: enhancement

#142 Custom theme examples
  docs/docs/customization/_category_.json
  docs/docs/customization/theme.md
  packages/generator-xplorer-theme/example/Purple/README.md
  packages/generator-xplorer-theme/example/Purple/package.json
  packages/generator-xplorer-theme/example/Purple/purple.js
  packages/generator-xplorer-theme/example/README.md
  packages/generator-xplorer-theme/example/Sky/README.md
  packages/generator-xplorer-theme/example/Sky/package.json
  packages/generator-xplorer-theme/example/Sky/sky.js
  src/Extensions/registerTheme.ts
Labels: hacktoberfest-accepted

#135 Reduce duplicated code
  .gitignore
  src/Components/Files/File Operation/select.ts
  src/Components/Functions/lazyLoadingImage.ts
  src/Components/Theme/theme.ts
Labels: code style, changes requested
